# Generated by Django 2.2.5 on 2019-09-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('issue_a', models.CharField(default='agree', max_length=300)),
                ('issue_b', models.CharField(default='disagree', max_length=300)),
                ('image_a', models.ImageField(default=None, upload_to='')),
                ('image_b', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete='CASCADE', to='eithers.Question')),
            ],
        ),
    ]
